### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by CreativeDive** [WPTRT/theme-sniffer#80]
Hey,

I've installed this plugin and there is something wrong. I have a domain with different subfolders and each subfolder have a own WordPress installation. So I have installed this plugin for testing in one of my subfolders wordpress installation. After activating and starting the theme sniffer test by clicking the GO button, nothing is happened. I get this in the browser console error:

> Failed to load resource: the server responded with a status of 403 (Forbidden)
> http://www.domain.de/wp-json/theme-sniffer/v1/sniff-run 

`{"code":"rest_no_route","message":"Keine Route f\u00fcr URL und Request-Methode gefunden","data":{"status":404}}`

Why the plugin search for a folder outside of this wordpress installation? The right path is:

> http://www.domain.de/my-wp-installation-one/wp-json/theme-sniffer/v1/sniff-run

**Comment by joyously** [comment]
Hey, that might be why I could never get it to run on my local install, which has WP in subfolders.

**Comment by dingo-d** [comment]
Are you using the official release [v0.1.4](https://github.com/WPTRT/theme-sniffer/releases/download/0.1.4/ns-theme-check.0.1.4.zip)?

Or are you using the github version that you installed manually?

**Comment by dingo-d** [comment]
Ok I tried with the plugin pulled from the github, and indeed the REST version is not working with the subfolders. Good thing is that the official release will work, so you can work with that. There could be a solution as outlined here: https://github.com/WP-API/WP-API/issues/808 (haven't tested this). 

I'll search the trac for an issue about this.

**Comment by CreativeDive** [comment]
@dingo-d yes I'm using the latest version v0.1.4 from github. The official release is working 👍 
 Thank you for trying to fix the problem. Why the github version is called "Theme Sniffer" and the official release is called "NS Theme Check"? :-D

**Comment by dingo-d** [comment]
There was a change a while back, and the zip file hasn't been updated. We still have work to do on the plugin :)

**Comment by dingo-d** [comment]
Ok, I got the answer on WPSO and the ajax method has a wrong hardcoded value for REST route. But this should be fixed when the #79 PR is merged.

**Comment by CreativeDive** [comment]
@dingo-d when will the new version be released? :-)

**Comment by CreativeDive** [comment]
A other issue is, that the path of each file is missing by the theme check. You can see it in the following screenshot (wp-content/hannah/[missing-file])

<img width="775" alt="bildschirmfoto 2017-12-30 um 11 05 29" src="https://user-images.githubusercontent.com/31563167/34453305-6558cf54-ed51-11e7-8d08-c657abedfd00.png">

**Comment by dingo-d** [comment]
I'll take a look at it later and check if the same happens for me, and fix the PR. I'm not sure when the next release will be done. I'm waiting for the PR to be approved. Once that's done I still need to rewrite the whole plugin to be namespaced and to use autoloader. 

I'd leave that for 0.15 version, or later on. We'll see next year :D

**Comment by CreativeDive** [comment]
@dingo-d is there any new information about updating theme sniffer to the new version? :-)

**Comment by dingo-d** [comment]
I'm still waiting for a PR approval and merge, once this happens, It will be available. In the meantime, if you want updated version, you can just checkout my branch (`dingo-d:feature/rewrite-plugin-webpack` https://github.com/dingo-d/theme-sniffer/tree/feature/rewrite-plugin-webpack)

**Comment by dingo-d** [comment]
@CreativeDive we released the 0.1.5 version, can you download it and test it? Thanks!

**Comment by CreativeDive** [comment]
@dingo-d I've installed the new 0.1.5 version. The issue with a wordpress installation in a subfolder is solved 👍 

But the missing file path issue is not solved 👎 

![path-issue](https://user-images.githubusercontent.com/31563167/35486768-ff6dfcf8-0472-11e8-81e0-e68d07da716f.jpg)

And a new issue is there. The test will aborted after 22,32% 👎 In the pre version the test is completed finished.

<img width="1007" alt="bildschirmfoto 2018-01-28 um 21 36 15" src="https://user-images.githubusercontent.com/31563167/35486780-4a250b60-0473-11e8-8477-7a53c349eae4.png">

**Comment by dingo-d** [comment]
Will check this out asap. Thanks for testing it!

**Comment by dingo-d** [comment]
@CreativeDive Just for the reference, this is a custom theme that you are testing, or? I couldn't find it in the theme directory, or in the theme review trac repo.

**Comment by CreativeDive** [comment]
@dingo-d yes it's a custom theme. With Twenty Fifteen the test will completely finished.

With the custom theme, I get this errors in the console:

<img width="964" alt="bildschirmfoto 2018-01-28 um 22 09 35" src="https://user-images.githubusercontent.com/31563167/35487077-f55d0a56-0477-11e8-9db2-26016a79f8f3.png">

Do you need this theme for testing? I can send you a link via email.

**Comment by CreativeDive** [comment]
@dingo-d maybe the reason of this issue is the file size? The "acf-field-groups.php have 21618 lines ;-)

**Comment by dingo-d** [comment]
Big size can indeed be an issue, but from the link, it could also be an issue in the encoded link to the theme file. You can send the theme to me, the email is denis.zoljom[at]gmail.com

**Comment by CreativeDive** [comment]
@dingo-d ok, has you tested the file path issue with a wordpress installation which is located in a subfolder?

I have the Google Chrome (63.0.3239.132) browser on Mac OS High Sierra (10.13.2), WordPress 4.9.2, PHP 7.1.13

Ok, I have send you an email with a download link.

**Comment by dingo-d** [comment]
Ok, I've ran your theme on my local vagrant and it broke on the `acf-field-groups.php`file which is 21618 lines long.

> <b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) ....

So the issue is with too big files. In the next version I'll have to add a skip if the file is to big.
The subfolder issue should be fixed, the issue was in the path to the endpoint that runs the sniff, but that issue should be fixed.

**Comment by CreativeDive** [comment]
@dingo-d That sounds great. I will wait for the next version 👍
